version: "3.3"
services:
  database:
    image: mysql
    container_name: dishdiarydb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER="root"
      - MYSQL_ROOT_PASSWORD="nabin105838"
      - MYSQL_DATABASE="dish_diaries_app"
    ports:
      - 3307:3306
    volumes:
      - ./dd-database:/var/lib/mysql
  frontend:
    image: my-vue-app
    container_name: dishdiaryfront
    build: ./dd-frontend
    ports:
      - 80:80
  backend:
    image: my-node-app
    container_name: dishdiaryback
    restart: on-failure
    build: ./dd-backend
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  dd-database:


