openapi: 3.0.0
info:
  title: Dish Diary API
  description: Optional multiline or single-line description in CommonMark or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080/
  - url: http://10.4.85.10:8080/
paths:
  /api/recipe:
    get:
      summary: Returns a list of recipes.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipe:
                  type: string
      responses:
        "201":
          description: Created
