openapi: 3.0.0
info:
  title: Dish Diary API
  description: Optional multiline or single-line description in CommonMark or HTML.
  version: 0.1.9
servers:
  - url: http://10.4.85.10:8080/
paths:
  /api/recipe:
    get:
      summary: Returns a list of recipes.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                recipeName:
                  type: string
                cookingSteps:
                  type: string
                cookingIngredients:
                  type: string
                introduce:
                  type: string
                categoryId:
                  type: string
                recipeImage:
                  type: string
                  format: binary
      responses:
        "201":
          description: Created

  /api/recipe/{recipeId}:
    parameters:
      - name: recipeId
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Updates a recipe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                introduce:
                  type: string
                cookingIngredients:
                  type: string
                cookingSteps:
                  type: string
      responses:
        "200":
          description: OK
        "404":
          description: Recipe not found
    delete:
      summary: Deletes a recipe.
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "404":
          description: Recipe not found
